/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ui;

import com.parser.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DesktopManager;

/**
 *
 * @author vigneshm
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorChangeWindow = new javax.swing.JDesktopPane();
        authorChangeFrame = new javax.swing.JInternalFrame();
        authorListPane1 = new javax.swing.JScrollPane();
        authorListOrig = new javax.swing.JList();
        authorListPane2 = new javax.swing.JScrollPane();
        authorListNew = new javax.swing.JList();
        AddOneBtn = new javax.swing.JButton();
        DelAllBtn = new javax.swing.JButton();
        AddAllBtn = new javax.swing.JButton();
        DelOneBtn = new javax.swing.JButton();
        mainFrame = new javax.swing.JInternalFrame();
        mainScroll = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        authorNameLabel = new javax.swing.JLabel();
        authorNameInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        tostringtoggle = new javax.swing.JCheckBox();
        resultnumLabel = new javax.swing.JLabel();
        resultnumInput = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        sortByDateBtn = new javax.swing.JButton();
        sortByCitBtn = new javax.swing.JButton();
        sortDateStatus = new javax.swing.JLabel();
        sortCitStatus = new javax.swing.JLabel();
        authorChangeBtn = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        authorChangeWindow.setBackground(new java.awt.Color(255, 255, 255));

        authorChangeFrame.setVisible(true);

        authorListOrig.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        authorListOrig.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        authorListPane1.setViewportView(authorListOrig);

        authorListNew.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        authorListPane2.setViewportView(authorListNew);

        AddOneBtn.setText(">");

        DelAllBtn.setText("<<");

        AddAllBtn.setText(">>");

        DelOneBtn.setText("<");

        javax.swing.GroupLayout authorChangeFrameLayout = new javax.swing.GroupLayout(authorChangeFrame.getContentPane());
        authorChangeFrame.getContentPane().setLayout(authorChangeFrameLayout);
        authorChangeFrameLayout.setHorizontalGroup(
            authorChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authorChangeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorListPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authorChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DelOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DelAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorListPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        authorChangeFrameLayout.setVerticalGroup(
            authorChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authorChangeFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(authorChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(authorListPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorListPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(authorChangeFrameLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AddOneBtn)
                .addGap(14, 14, 14)
                .addComponent(AddAllBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DelOneBtn)
                .addGap(18, 18, 18)
                .addComponent(DelAllBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        authorChangeWindow.add(authorChangeFrame);

        mainFrame.setVisible(true);

        mainTextArea.setEditable(false);
        mainTextArea.setColumns(20);
        mainTextArea.setLineWrap(true);
        mainTextArea.setRows(5);
        mainTextArea.setWrapStyleWord(true);
        mainScroll.setViewportView(mainTextArea);

        authorNameLabel.setText("Author name : ");

        authorNameInput.setText("Enter name : ");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        tostringtoggle.setText("More Info");
        tostringtoggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tostringtoggleActionPerformed(evt);
            }
        });

        resultnumLabel.setText("Number of results :");

        resultnumInput.setText("10");
        resultnumInput.setToolTipText("");

        sortByDateBtn.setText("Sort By Date");
        sortByDateBtn.setActionCommand("Sort By Year");
        sortByDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByDateBtnActionPerformed(evt);
            }
        });

        sortByCitBtn.setText("Sort By Citation");
        sortByCitBtn.setLabel("Sort By Citation\nCount");
        sortByCitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByCitBtnActionPerformed(evt);
            }
        });

        sortDateStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/up_arrow.png"))); // NOI18N
        sortDateStatus.setName("inc"); // NOI18N

        sortCitStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/up_arrow.png"))); // NOI18N
        sortCitStatus.setName("inc"); // NOI18N

        authorChangeBtn.setText("Choose Authors");
        authorChangeBtn.setToolTipText("");
        authorChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorChangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame.getContentPane());
        mainFrame.getContentPane().setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(authorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorNameLabel)))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tostringtoggle)))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(resultnumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultnumLabel))))
                .addGap(3, 3, 3)
                .addComponent(mainScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sortByCitBtn)
                                .addGap(46, 46, 46))
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sortByDateBtn)
                                    .addComponent(authorChangeBtn))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(sortDateStatus))
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(sortCitStatus)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainFrameLayout.createSequentialGroup()
                    .addGap(0, 336, Short.MAX_VALUE)
                    .addComponent(errorLabel)
                    .addGap(0, 335, Short.MAX_VALUE)))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(authorNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortByDateBtn)
                        .addGap(18, 18, 18)))
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(resultnumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultnumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tostringtoggle))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(sortDateStatus)
                        .addGap(18, 18, 18)
                        .addComponent(sortByCitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortCitStatus)))
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn)
                        .addGap(113, 113, 113))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(authorChangeBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScroll)
                .addContainerGap())
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainFrameLayout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(errorLabel)
                    .addGap(0, 167, Short.MAX_VALUE)))
        );

        authorChangeWindow.add(mainFrame);

        jToolBar1.setRollover(true);
        authorChangeWindow.add(jToolBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(authorChangeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(authorChangeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static EntryList currentlist;
    static int displaymode;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String authorname=authorNameInput.getText();
        String numresultstr=resultnumInput.getText();
        mainTextArea.setText("Fetching results . . . ");
        errorLabel.setText("");
        int numresult;
        try{
            numresult=Integer.parseInt(numresultstr.trim());
            currentlist=parser.parsePage(1, authorname, numresult);
            updateText(1);
        } catch(NumberFormatException e){
            errorLabel.setText("Enter a proper number !");
        } catch(Exception e){
            ;
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tostringtoggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tostringtoggleActionPerformed
        if(tostringtoggle.isSelected()) {
            updateText(2);
            //tostringtoggle.setText("Less info");
        } else {
            updateText(1);
            tostringtoggle.setText("More info");
        }
    }//GEN-LAST:event_tostringtoggleActionPerformed

    private void sortByDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByDateBtnActionPerformed
        boolean asc=!sortDateStatus.getName().equals("dec");
        if(asc){
            sortDateStatus.setName("dec");
            sortDateStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/down_arrow.png"))); 
        } else {
            sortDateStatus.setName("inc");
            sortDateStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/up_arrow.png"))); 
        }
        System.out.println(asc);
        currentlist.sortByYear(asc);
        updateText();
    }//GEN-LAST:event_sortByDateBtnActionPerformed

    private void sortByCitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByCitBtnActionPerformed
        boolean asc=!sortCitStatus.getName().equals("dec");
        if(asc){
            sortCitStatus.setName("dec");
            sortCitStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/down_arrow.png"))); 
        } else {
            sortCitStatus.setName("inc");
            sortCitStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ui/up_arrow.png"))); 
        }
        System.out.println(asc);
        currentlist.sortByCitations(asc);
        updateText();
    }//GEN-LAST:event_sortByCitBtnActionPerformed

    private void authorChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorChangeBtnActionPerformed
        authorchange();
    }//GEN-LAST:event_authorChangeBtnActionPerformed
    private void updateText(int newmode){
        //mode  1 - basic , 2 - verbose 
        displaymode=newmode;
        mainTextArea.setText("");
        for(Entry e:currentlist){
            if(displaymode==1) mainTextArea.append(e.toString_basic()+"\n");
            if(displaymode==2) mainTextArea.append(e.toString()+"\n");
        }
    }
    private void updateText(){
        //mode  1 - basic , 2 - verbose 
        mainTextArea.setText("");
        for(Entry e:currentlist){
            if(displaymode==1) mainTextArea.append(e.toString_basic()+"\n");
            if(displaymode==2) mainTextArea.append(e.toString()+"\n");
        }
    }
    private void authorchange(){
        DesktopManager dm=authorChangeWindow.getDesktopManager();
        dm.openFrame(authorChangeFrame);
        try {
            authorChangeFrame.setSelected(true);
        } catch (PropertyVetoException ex) {
            System.out.println("Cant print");
        }
        authorChangeWindow.setVisible(true);
        authorChangeFrame.setVisible(true);
        authorListOrig.setListData(new String[]{"sdc","asd"});
        authorListNew.setListData(new String[]{"acs","iuh"});
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame main=new MainFrame();
                main.setVisible(true);
                DesktopManager dm=main.authorChangeWindow.getDesktopManager();
                dm.openFrame(main.authorChangeFrame);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAllBtn;
    private javax.swing.JButton AddOneBtn;
    private javax.swing.JButton DelAllBtn;
    private javax.swing.JButton DelOneBtn;
    private javax.swing.JButton authorChangeBtn;
    private javax.swing.JInternalFrame authorChangeFrame;
    private javax.swing.JDesktopPane authorChangeWindow;
    private javax.swing.JList authorListNew;
    private javax.swing.JList authorListOrig;
    private javax.swing.JScrollPane authorListPane1;
    private javax.swing.JScrollPane authorListPane2;
    private javax.swing.JTextField authorNameInput;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame mainFrame;
    private javax.swing.JScrollPane mainScroll;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JTextField resultnumInput;
    private javax.swing.JLabel resultnumLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton sortByCitBtn;
    private javax.swing.JButton sortByDateBtn;
    private javax.swing.JLabel sortCitStatus;
    private javax.swing.JLabel sortDateStatus;
    private javax.swing.JCheckBox tostringtoggle;
    // End of variables declaration//GEN-END:variables
}
